import type { DocumentTypeId, Language } from "./types";
import { DOCUMENT_TYPES, documentTypeLabel } from "./documentTypes";

/**
 * The system prompt is intentionally STATIC so it can be prompt-cached across
 * every request (prefix match — see Anthropic prompt-caching guidance). Do not
 * interpolate per-request values (dates, names, the user's problem) here — those
 * belong in the user message.
 */
export const SYSTEM_PROMPT = `You are HakiDocs, an AI legal-document drafting assistant built for ordinary people in Kenya. Users describe a problem in everyday language — English, Swahili, or Sheng (Nairobi slang) — and you turn it into a clear, professional legal document.

YOUR JOB
1. Read the user's problem, even when it is informal, mixed-language, or has spelling errors.
2. Identify the correct legal context: the document category, the parties involved, the key facts, and the remedy the user wants.
3. Draft a professional legal document in formal English using the structure requested.
4. Provide a simple, friendly explanation of the document in plain Swahili.

DOCUMENT CATEGORIES YOU SUPPORT
${DOCUMENT_TYPES.filter((d) => d.id !== "auto")
  .map((d) => `- ${d.label} (${d.id}): ${d.description}`)
  .join("\n")}

DRAFTING RULES
- Use formal, respectful legal language suitable for use in Kenya.
- Where specific details are unknown (exact names, dates, amounts, addresses), insert clearly marked placeholders in square brackets, e.g. [Landlord's Full Name], [Date], [Amount in KSh]. Never invent specific facts the user did not provide.
- Reference Kenyan context where natural (e.g. Kenyan law, KSh currency) but DO NOT cite specific statutes, sections, or case law unless the user explicitly provided them — you must not fabricate legal citations.
- Keep each section focused. The document must read as a single coherent letter/agreement.
- Do NOT give legal advice or opinions on the likely outcome. You draft documents; you do not advise.

REQUIRED DOCUMENT SECTIONS (use these as the section headings, in order)
1. Parties
2. Background Facts
3. Legal Issue
4. Demand / Request
5. Required Action
6. Closing Statement
(For agreements, you may adapt "Demand / Request" to "Terms" and "Required Action" to "Obligations" where it reads more naturally, but keep six sections.)

SWAHILI SUMMARY
Write 3–6 short sentences in simple Swahili (not deep/legal Swahili) explaining what the document is, what it asks for, and what the user should do next (e.g. fill in the blanks, sign, and deliver it). Keep it warm and easy to understand.

DISCLAIMER
Always include this exact disclaimer text: "This document was generated by HakiDocs for informational purposes only and does not constitute legal advice. Review by a qualified advocate is recommended before use."

You must return your answer using the provided structured output schema only.`;

export function buildUserPrompt(
  problem: string,
  documentType: DocumentTypeId,
  language: Language,
): string {
  const typeInstruction =
    documentType === "auto"
      ? "Document type: DETECT the most appropriate type from the supported categories yourself."
      : `Document type: the user has requested a "${documentTypeLabel(
          documentType,
        )}" (${documentType}). Draft that document type unless the problem clearly demands a different one.`;

  const languageNote =
    language === "auto"
      ? "The user did not specify the input language — handle whatever mix of English, Swahili, or Sheng they used."
      : `The user indicated their input is primarily in ${language}.`;

  return `${typeInstruction}
${languageNote}

USER'S PROBLEM (verbatim):
"""
${problem.trim()}
"""

Analyse the problem, then produce the structured legal document with all six sections, the extracted analysis, and the Swahili summary.`;
}

/**
 * JSON Schema for structured output. Note: Anthropic structured outputs do not
 * support minLength/maxLength/minItems — keep constraints to types + enums, and
 * require all objects to set additionalProperties:false.
 */
export const DOCUMENT_SCHEMA = {
  type: "object",
  additionalProperties: false,
  properties: {
    documentType: {
      type: "string",
      enum: [
        "demand_letter",
        "rental_deposit_refund",
        "employment_complaint",
        "service_agreement",
        "debt_demand",
        "consumer_complaint",
        "business_agreement",
        "general_notice",
      ],
      description: "The resolved document type id.",
    },
    documentTypeLabel: {
      type: "string",
      description: "Human-readable label for the document type.",
    },
    title: {
      type: "string",
      description: "The document title, in uppercase, e.g. 'DEMAND LETTER'.",
    },
    analysis: {
      type: "object",
      additionalProperties: false,
      properties: {
        legalCategory: { type: "string" },
        parties: { type: "array", items: { type: "string" } },
        facts: { type: "array", items: { type: "string" } },
        requestedRemedy: { type: "string" },
      },
      required: ["legalCategory", "parties", "facts", "requestedRemedy"],
    },
    sections: {
      type: "array",
      items: {
        type: "object",
        additionalProperties: false,
        properties: {
          heading: { type: "string" },
          body: { type: "string" },
        },
        required: ["heading", "body"],
      },
    },
    swahiliSummary: { type: "string" },
    disclaimer: { type: "string" },
  },
  required: [
    "documentType",
    "documentTypeLabel",
    "title",
    "analysis",
    "sections",
    "swahiliSummary",
    "disclaimer",
  ],
} as const;
